default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  host: <%= ENV['MARCHAND_DEV_DB_HOST'] %>
  port: <%= ENV['MARCHAND_DEV_DB_PORT'] %>
  database: <%= ENV['MARCHAND_DEV_DB'] %>
  pool: 10
  username: <%= ENV['MARCHAND_DEV_DB_USER'] %>
  password: <%= ENV['MARCHAND_DEV_DB_PASSWORD'] %>
  reconnect: true

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  host: <%= ENV['MARCHAND_PROD_DB_HOST'] %>
  port: <%= ENV['MARCHAND_PROD_DB_PORT'] %>
  database: <%= ENV['MARCHAND_PROD_DB'] %>
  pool: 10
  username: <%= ENV['MARCHAND_PROD_DB_USER'] %>
  password: <%= ENV['MARCHAND_PROD_DB_PASSWORD'] %>
  reconnect: true
